services:
  - type: web
    name: plan-b-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: .next
    envVars:
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
        sync: false
      - key: NEXT_PUBLIC_ALPHA_VANTAGE_API_KEY
        sync: false
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://plan-b-backend.onrender.com 