services:
  # 後端服務
  - type: web
    name: plan-b-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: ALPHA_VANTAGE_API_KEY
        sync: false
      - key: FINNHUB_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false

  # 前端服務
  - type: web
    name: plan-b-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: .next
    envVars:
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        sync: false
      - key: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
        sync: false
      - key: NEXT_PUBLIC_ALPHA_VANTAGE_API_KEY
        sync: false
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://plan-b-backend.onrender.com 